[project]
name = "assignment2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "keras>=3.6.0",
    "matplotlib>=3.9.2",
    "numpy>=2.0.2",
    "tensorflow[and-cuda]>=2.18.0",
]
